<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="PLC_PRG" Id="{f9234ef3-7125-42f2-9743-bf9e8fd2c250}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PLC_PRG
VAR
	fbWriteStr						:BFB_WriteStrToFile;
	fbWriteWstr						:BFB_WriteWstrToFile;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbWriteStr.bBusy

fbWriteWstr.bDone]]></ST>
    </Implementation>
    <LineIds Name="PLC_PRG">
      <LineId Id="5" Count="0" />
      <LineId Id="11" Count="0" />
      <LineId Id="10" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>